# Generated by Django 4.2.5 on 2023-09-25 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
