# Generated by Django 4.2.4 on 2023-08-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_alter_item_shoppinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['completed'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['created'], 'verbose_name': 'shopping list', 'verbose_name_plural': 'shopping lists'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='shoppinglist',
        ),
        migrations.AddField(
            model_name='item',
            name='shopping_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shoppinglist.shoppinglist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruits and vegetables', 'fruits and vegetables'), ('meat', 'meat'), ('diary', 'diary'), ('dry goods', 'dry goods'), ('alcohols', 'alcohols'), ('medicine', 'medicine'), ('pet goods', 'pet goods'), ('baby goods', 'baby goods'), ('domestic detergents', 'domestic detergents'), ('ready-cook meals', 'ready-cook meals'), ('hygiene', 'hygiene'), ('coffee & tea', 'coffee & tea'), ('frozen foods', 'frozen foods'), ('garden and tinkering', 'garden and tinkering'), ('bread', 'bread'), ('preserves', 'preserves'), ('spices, sauces, additives', 'spices, sauces, additives'), ('fishes and seafood', 'fishes and seafood'), ('sweets and snacks', 'sweets and snacks'), ('fats', 'fats'), ('water and drinks', 'water and drinks'), ('dried fruit and nuts', 'dried fruit and nuts'), ('fresh herbs', 'fresh herbs'), ('canned food', 'canned food'), ('other', 'other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pcs'), ('pkgs', 'pkgs'), ('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
