# Generated by Django 4.2.4 on 2023-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_alter_item_options_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruits and vegetables', 'Fruits Vegetables'), ('meat', 'Meat'), ('diary', 'Diary'), ('dry goods', 'Dry Goods'), ('alcohols', 'Alcohols'), ('medicine', 'Medicine'), ('pet goods', 'Pet Goods'), ('baby goods', 'Baby Goods'), ('domestic detergents', 'Domestic Detergents'), ('ready-cook meals', 'Ready Cook Meals'), ('hygiene', 'Hygiene'), ('coffee & tea', 'Coffee Tea'), ('frozen foods', 'Frozen Foods'), ('garden and tinkering', 'Garden Tinker'), ('bread', 'Bread'), ('preserves', 'Preserves'), ('spices, sauces, additives', 'Spices'), ('fishes and seafood', 'Fish'), ('sweets and snacks', 'Sweets'), ('fats', 'Fats'), ('water and drinks', 'Drinks'), ('dried fruit and nuts', 'Nuts'), ('fresh herbs', 'Herbs'), ('canned food', 'Cans'), ('other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('pkgs', 'Packages'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter')], max_length=20, null=True),
        ),
    ]
