# Generated by Django 4.2.4 on 2023-09-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0005_alter_item_category_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoppinglist.shoppinglist'),
        ),
    ]
